while True:
    try:
        2 + 2
    except Exception as e:
        print(e)
